### ISSUE TITLE
Data processes

### ISSUE THREAD

**Issue by TnakaNY** [ShixiangWang/prad_signature#10]
Hi,
I read your manuscript. Nice work! I am interested in CN sig analysis. To learn how to, I tried to analyze same MSKCC dataset. 

I have some questions. From cbioportal, I downloaded MSKCC 2020 PC 1465 results.
Then, i checked "data_cna_hg19.seg" to get input data for ABSOLUTE as you mentioned in the manuscript.
ID | chrom | loc.start | loc.end | num.mark | seg.mean
-- | -- | -- | -- | -- | --
P-0011577-T01-IM5 | 1 | 2488138 | 1.5E+08 | 386 | 0.0414
P-0011577-T01-IM5 | 1 | 1.51E+08 | 1.56E+08 | 10 | 0.3618
P-0011577-T01-IM5 | 1 | 1.56E+08 | 2.46E+08 | 202 | 0.0459
P-0011577-T01-IM5 | 2 | 4717089 | 1.35E+08 | 258 | -0.0244

ABSOLUTE input are "Chromosome", "Start","End","Num_Probes","Segment_Mean" with MAF file.

How did you fit "data_cna_hg19.seg" to ABSOLUTE input dataform. Can i use num.mark as "Num_Probes"?
How did you make MAF files from cbioportal download data?

I am beginner for NGS data handling. Any infor will be very helpful for me.

Thank you in advance.
Thanks.

**Comment by TnakaNY** [comment]
I just found "data_mutations_extended.txt" is the MAF file. 
If "num.mark" is acceptable as Num.Probes, can I analyze all sample by ABSOLUTE using your package "DoABSOLUTE", parallelly?

**Comment by ShixiangWang** [comment]
@TnakaNY Thanks for your interest, the following code may help.

```
seg_tumor <- file.path(data_dir, "prad_mskcc_2020/data_cna_hg19.seg")            # segment file
maf_tumor <- file.path(data_dir, "prad_mskcc_2020/data_mutations_extended.txt")  # MAF file

Seg <- fread(seg_tumor)
colnames(Seg)
colnames(Seg) <- c("Sample", "Chromosome", "Start", "End", "Num_Probes", "Segment_Mean")
Maf <- fread(maf_tumor, skip = 2)
colnames(Maf)

# Run DoAbsolute
library(DoAbsolute)
DoAbsolute(
  Seg = Seg, Maf = Maf, platform = "Illumina_WES",
  copy.num.type = "total",
  primary.disease = "PRAD",
  max.as.seg.count = 10000, # Keep all samples processed by ABSOLUTE
  temp.dir = "output/DoAbsolute_mskcc_2020",
  results.dir = "output/DoAbsolute_mskcc_2020", nThread = 20,
  keepAllResult = TRUE, verbose = TRUE
)
```

**Comment by TnakaNY** [comment]
Thank you very much for your prompt comment!
absoluteCNV.Rdata of Pancan12 also looks nice!

**Comment by ShixiangWang** [comment]
You are welcome.
